title: <center> Distributed, Decentralized, and Asynchronous Machine Learning </center>
email: njkrichardson@princeton.edu
description: 
  <center> Workshop organization site for Distributed, Decentralized, and Asynchronous Machine Learning (DDA), 
  which we hope to host at ICLR 2025 at the Singapore EXPO. </center> 
url: "" 
github_username: njkrichardson

navigation:
  Home: "/"
  Call for Papers: "/"
  Speakers: "/"
  Organizers: "/"
  Schedule: "/"
  Accepted Papers: "/"

plugins:
  - jekyll-feed

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true
